### ISSUE TITLE
Not supported block of terracta (hardened clay) ?

### ISSUE THREAD

**Issue by foxdog05000** [FlorianFe/PaperCubes#1] opened 2018-02-03 11:16 UTC
Hello, I love your app !

I performed several tests with different structures and blocks on Minecraft 1.12. The result is really great!
But I noticed that not all blocks are supported at the moment ? Like terracota (hardened clay) for example. 

On the other hand with wool everything works well !

I created a schematic of this iron golem.

![2018-02-03_12 05 25](https://user-images.githubusercontent.com/18735549/35766563-222e6c3e-08db-11e8-82f7-dd9ba55f60bc.png)

Link to shematic : https://drive.google.com/open?id=15ymlycr5MUmtETCDi2f2mUTHU3hmNzyu

And I didn't get the expected result when I used your app. Hey, what's going on ?
![image](https://user-images.githubusercontent.com/18735549/35766587-8315b1e2-08db-11e8-8936-714f9f7d96d4.png)

**Comment by FlorianFe** [comment] 2018-02-03 13:15
Hello foxdog05000, 

thanks for letting me know about this issue. It seems like all the blocks with an ID of above 127 (like the Terracotta Block with 159) will be interpreted as Air, so you just can see the parts of the iron golem which have an ID smaller than 128, which is just the stone block. I guess the problem is because I interpret an "unsigned char" as a normal "char" somewhere. 

Whatever it is I will fix it in the next version :)

**Comment by foxdog05000** [comment] 2018-02-03 13:20
Thank you for your time and explanations. I'll wait until the problem is fixed !

**Comment by FlorianFe** [comment] 2018-02-03 17:29
The problem should be fixed in the new version 1.1.3 Beta now =)

![image](https://user-images.githubusercontent.com/19766850/35769710-5e06a2ce-090f-11e8-91df-8d71a47160ae.png)

**Closed by FlorianFe** 2018-02-03 17:29 UTC

**Comment by foxdog05000** [comment] 2018-07-28 11:38
Hi, I'm reopening this issue to show you the finished construction!! I spent a lot of time putting all this together but the result is great ! Thanks !

![sam_1063](https://user-images.githubusercontent.com/18735549/43356110-ff3bb564-926a-11e8-83cc-06067cccc36b.JPG)

**Comment by FlorianFe** [comment] 2018-07-29 09:10
Awesome!!! :D
